### ISSUE TITLE
Quad Autocannon 

### ISSUE THREAD

**Issue by barbramt** [BSData/aeronautica-imperialis#1]
Quad Autocannon has wrong stats in Imperial_Navy.cat
0-2-1
2+
not
2-6-0
4+

**Comment by Guy-Markman** [comment]
Thank you, will fix it in the next update.

**Comment by barbramt** [comment]
no worries i forked, changed and did pull request. there is only master branch though so i did it to that.

**Comment by Guy-Markman** [comment]
Fixed by you at #2
