### ISSUE TITLE
Marauder Destroyer Rear Turret

### ISSUE THREAD

**Issue by David-Hunt77** [BSData/aeronautica-imperialis#10]
Hi,

The data shows the Marauder Destroyer Rear Turret FPR as 3-2-0 (same as the bomber) but according to the book its 6-3-0.

Thanks

David
![MarauderDestroyer](https://user-images.githubusercontent.com/55692402/66146009-cf605c80-e603-11e9-8b95-f630d36dca6c.JPG)

**Comment by Guy-Markman** [comment]
Oh, I thought it had the same one as Marauder. Thanks, I’ll fix it.

**Comment by Guy-Markman** [comment]
Fixed in #14
