### ISSUE TITLE
[Request] Ares Gunship in Imperial Navy and Astartes squadrons

### ISSUE THREAD

**Issue by Ardias-03** [BSData/aeronautica-imperialis#108]
Would it be possible to get the Ares Gunship added to the Imperial Navy and Astartes squadron lists? It was in the new Heresy book, but also seems to fit in the 40k-Indomitus era as well

**Comment by evanh** [comment]
Are Ares allowed to be allied into Imperial and Astartes squadrons?

**Comment by Ardias-03** [comment]
Yep:
"Ares Gunships can be taken in a Legiones Astartes or Divisio Aeronautica force, or in a force consisting entirely of Ares Gunships.  They may take the standard Legiones Astartes aircraft upgrades and gain Legiones Astartes pilot Ace Abilities in campaigns..."

**Comment by evanh** [comment]
This should be addressed as part of https://github.com/BSData/aeronautica-imperialis/issues/103. I'm going to close this issue in favour of that.
