### ISSUE TITLE
[Anon] Usability: Vulture additional weaponry selecting not intuitive

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/aeronautica-imperialis#16]
**File:** Ork_Air_Waaagh.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Within the Orcs selection - looks like can't add the additional weaponry correctly - can't see how to add the 2pts per bomb/rokkits selection on Dakkajet or fighta bomber

**Comment by barbramt** [comment]
I'm using Android with 2.03.17 with Ork waaagh v27 add the dakkajet or fighta bommer click the tick. Now click the 3 dots and select edit
dakkajet has additional weapons click the arrows and add required
fighta bommer has additional weapons click the circle and you get none, 3 small weapons or big bomb. click circle for 3 small weapons and then the tick. now click the additional weapons it will give you  the arrows  to click and add as required

It appears to be just a few more steps for the fighta bommer over the dakkajet. make sure to have the latest version of data as well.

**Comment by Guy-Markman** [comment]
I'll rework that logic so It'll be more intuitive

**Comment by ShaneRing11** [comment]
While adding the Taros content I came across a similar situation with the Vulture (can either choose a twin linked lascannon, 0-2 rocket pods, or 0-3 bomb/missile cradles) and I wasn't able to come up with a different solution. If anyone does in the future, please change the Vulture profile in the Astra Militarum catalogue to make sure they're consistent.

**Comment by ShaneRing11** [comment]
With the new FAQ changing how Ork Bommer weapon options work this is no longer an issue on those profiles, however this method of selection is still present on the Vulture as mentioned in the previous comment. Given this the title isn't accurate to the issue anymore I've gone ahead and renamed it.

**Comment by Mad-Spy** [comment]
This should now be sorted following the merge of #86
