### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by ShaneRing11** [BSData/aeronautica-imperialis#19]
Wanting to add Taros Air War content

**Comment by amis92** [comment]
Hello, @ShaneRing11. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
