### ISSUE TITLE
Facebook Issues

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/aeronautica-imperialis#3]
Issues found by Facebook Community: Edited over time

- [X] Kustom Big shootas and crews missing for some orks vehicles
- [X] Issue on fighta bombers with a limitation on weapons (Will be left to Ellie Bennett to fix as requsted by her).
- [X] Fire arcs on evy bomber, one should be right not left (Will be left to Ellie Bennett to fix as requsted by her).
- [X] No wing bombs on Fighta Bommer.
- [X] Forgot to add data for contact.
- [X] Executioner has crew options.
- [X] Kustom Big shoota costs 3 not 2.
- [X] Some side weapons missing their cost

**Comment by Guy-Markman** [comment]
- [ ] Executioner has crew options.
- [ ] Kustom Big shoota costs 3 not 2.

**Comment by barbramt** [comment]
Blue Devil has Crew options and Aircraft Upgrades options
Blue Devil missing Additional Weapons

**Comment by Guy-Markman** [comment]
All fixed in last version
