### ISSUE TITLE
Wazmek Speshul not applied correctly on Eavy Bommer

### ISSUE THREAD

**Issue by kingmt** [BSData/aeronautica-imperialis#52]
When applying the Wazmek Speshul to the Eavy Bommer the minimum speed is increased by 1, however the maximum speed is not increased.

Applying the Wazmek Speshul to a Dakkajet works as expected

**Comment by zopha** [comment]
What platform is this on? I've tested on desktop and it is working for me.

![image](https://user-images.githubusercontent.com/1666415/146766250-3b04bb5e-1aa0-4762-864c-3171fab15ed7.png)

I had a look at the editor and the conditions are the same as the Dakkajet.
![image](https://user-images.githubusercontent.com/1666415/146766378-259beb05-a4af-429c-a782-b8d93b2af1c1.png)

A full refresh of the files might fix it unless it's a platform specific bug.

**Comment by kingmt** [comment]
I am using the Mac OS desktop version and exporting the ros files to generate custom pdfs of the resulting aircraft. Maybe the error is in the XML generation?

**Comment by kingmt** [comment]
Wait, looking at that screen shot there is a decrement max speed by 1 in there. Is that correct?

**Comment by kingmt** [comment]
I made a mistake in reading the XML, closing the ticket
