### ISSUE TITLE
Astartes HK/Krak missiles are not currently supported

### ISSUE THREAD

**Issue by MadSkullz** [BSData/aeronautica-imperialis#55]
When replacing Astartes Rotary Frag Launcher, it does not correctly allow the user to select Krak or HK missiles. 

(This is almost certainly a time saving measure but I can't see the feature request so I'm raising it just in case)

**Comment by zopha** [comment]
It's nested so once you select Limited Missiles so once you select the option with Radio buttons, hit the tick and are back in the main Xiphon entry touch the text and it will give you the option to add missiles. For desktop you'll see Limited Missiles as bold, you can click on that and you'll get the sub menu.

**Comment by MadSkullz** [comment]
Thank you!

Tom Denyer | +447872 443173 | ***@***.***

**Comment by MadSkullz** [comment]
Hi Nial and thank you for your reply.

As per screenshot - it does not add the HK weapon profile even when one has
added 2xHK to the plane.

Is that working as expected? Screenshot attached

(And thank you again)

Tom Denyer | +447872 443173 | ***@***.***

**Comment by MadSkullz** [comment]
![Screenshot_20211223-172306](https://user-images.githubusercontent.com/96419522/147274393-6f655190-e634-45c1-831e-0d5bd8684189.jpg)

**Comment by zopha** [comment]
It should have the profile, I'll get that added in the next couple of days if no one else gets to it before me.

**Comment by MadSkullz** [comment]
Cheers dude and thanks for all the work you do for the community

Tom Denyer | +447872 443173 | ***@***.***
