### ISSUE TITLE
[Join Request] evanh

### ISSUE THREAD

**Issue by evanh** [BSData/aeronautica-imperialis#68]
I'm excited to play with the new Necron faction and I'd like to keep it up to date if I can help.

**Comment by evanh** [comment]
I already opened a PR for the Necron updates: https://github.com/BSData/aeronautica-imperialis/pull/67. I don't mind if someone else wants to merge it but I thought I should ask for permission just in case. 

Let me know if you need anything from me.

**Comment by zopha** [comment]
Thanks for the recent updates for Necrons and Asuryani!

I have no idea how to add people to the repos, I think I need a settings tab but I'm missing that. @ShaneRing11 @amis92 can you advise please?

**Comment by amis92** [comment]
@zopha upped your permissions, you should be able to `/invite` after you merge #73 :)

**Comment by zopha** [comment]
Thanks @amis92 , that's merged and I can see the settings tab but I can't find anything in settings to invite. Guides and toutrials make it look like there's a button missing or am I looking in the wrong place?

![image](https://user-images.githubusercontent.com/1666415/152939805-2208101b-4f3d-4f37-bf7b-9d9bde96d072.png)

**Comment by amis92** [comment]
Well there's a chat command https://github.com/BSData/chatops#invite-command and that's what I was referring to.

**Comment by zopha** [comment]
ahhhh, I see. I must read up on chatops, thanks!

/invite

**Comment by amis92** [comment]
@zopha It has to be the first line of a comment (a chatops command). And editing won't work, I think.
